- name: Create ansible user and add to sudo group
  hosts: new_server
  become: true

  vars:
    default_password: "{{ (lookup('file', lookup('env', 'PWD') ~ '/vault/var.vault') | from_yaml | default({})).ansible_user_pass }}"
    ansible_public_key: "{{ lookup('file', lookup('env', 'PWD') ~ '/resources/create_ansible_user/ansible.pub') }}"

  tasks:
    - name: Create user
      ansible.builtin.user:
        name: ansible
        state: present
        password: "{{ default_password | password_hash('sha512') }}"
        createhome: true
        shell: /bin/bash  # Establecer la shell como bash

    - name: Add user to sudo group
      ansible.builtin.user:
        name: ansible
        groups: sudo
        append: true

    - name: Ensure .ssh directory exists for ansible user
      ansible.builtin.file:
        path: "/home/ansible/.ssh"
        state: directory
        owner: ansible
        group: ansible
        mode: "0700"

    - name: Create authkeys file
      ansible.builtin.copy:
        content: "{{ ansible_public_key }}"
        dest: "/home/ansible/.ssh/authorized_keys"
        owner: ansible
        group: ansible
        mode: "0600"
...
