- name: Update packages
  hosts: all
  become: true

  tasks:
    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        autoremove: true
        autoclean: true
        update_cache: true
